runtime: php
env: flex

runtime_config:
  document_root: app.yaml

env_variables:
  MYSQL_DSN: mysql:host=icon;dbname=iconDb
  MYSQL_USER: icon
  MYSQL_PASSWORD: icon

handlers:
- url: /.*
  script: auto
